# Week 1 - Python Programming

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Additional References:
- [Google Colab](https://colab.research.google.com/?utm_source=scs-index)
- [Pandas Documentation](https://pandas.pydata.org/docs/index.html)
- [Python for Beginners](https://www.python.org/about/gettingstarted/)

## Business Understanding

-  Bank Churn: Customers that defaulted from the credit card company.
- Goal: Understand customers based on bank churn data.

## Data Understanding

### Preliminaries

Step 1. Set up project directory.

```
lastname_project
|---data                          # Directory for source data (*.csv)
    |---churn_test_20240126.csv   # Source data
|---notebook                      # Directory for Colab Notebook (*.ipynb)
    |---lastname_project.ipynb    # Colab Notebook
```

Step 2. Move source data into your Google Drive.

Step 3. Mount your Google Drive.

### Packages

In [4]:
#### Import packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Data

In [6]:
#### Read data
pdf = pd.read_csv('/content/drive/MyDrive/Work/PORTFOLIO/DATA ANALYTICS/Machine Learning Endeavor (Customer Churn)/data/churn_test_20240126.csv')

In [7]:
#### Basic information
pdf.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2026 entries, 0 to 2025
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CLIENTNUM               2026 non-null   int64
 1   Attrition_Flag          2026 non-null   int64
 2   Customer_Age            2026 non-null   int64
 3   Dependent_count         2026 non-null   int64
 4   Months_Inactive_12_mon  2026 non-null   int64
 5   Credit_Limit            2026 non-null   float64
 6   Total_Trans_Amt         2026 non-null   int64
dtypes: float64(1), int64(6)
memory usage: 110.9 KB

In [8]:
#### Shape
pdf.shape

(2026, 7)

In [9]:
#### Null
pdf.isnull().sum()

CLIENTNUM                 0
Attrition_Flag            0
Customer_Age              0
Dependent_count           0
Months_Inactive_12_mon    0
Credit_Limit              0
Total_Trans_Amt           0
dtype: int64

In [11]:
### Duplicate
pdf.duplicated().sum()

np.int64(0)

In [12]:
#### First 5 rows
pdf.head()

,CLIENTNUM,Attrition_Flag,Customer_Age,Dependent_count,Months_Inactive_12_mon,Credit_Limit,Total_Trans_Amt
0,719455083,0,48,3,3,2991.0,3734
1,773503308,0,59,1,5,2192.0,4010
2,715452408,0,37,2,3,1734.0,4727
3,711264033,0,47,3,2,4786.0,4973
4,718943508,0,42,3,3,3714.0,1454

### Profile